### ISSUE TITLE
NO SUPPORT WITH GRIEF PREVENTION 

### ISSUE THREAD

**Issue by notgman349yt** [jacky8399/PortableBeacons#2]
upon installing this plugin i saw that anyone can drop the nether stars on a beacon inside of a claimed area and take it, if you can add support for other plugins like grief prevention, towny ETC it would be much appreciated

**Comment by jacky8399** [comment]
The plugin does check if players can break the beacon and pyramid blocks using Bukkit events, but I will look into how GriefPrevention handles claimed area protection.

**Comment by jacky8399** [comment]
From my testing, as long as any block in the beacon pyramid is protected by a protection plugin, players can't pick them up. Mind providing more details?
