### ISSUE TITLE
Soul bound & setowner errors

### ISSUE THREAD

**Issue by ConsoleGods** [jacky8399/PortableBeacons#6]
I was trying to set the owner for a beacon and I used command /pb item setowner “Playername” “UUID/Playername” and got the error Index 4 out of bounds for length 4. And for the soul bound I did command /pb item add “Playername” soulbound 1 
But I also tried /pb item add “Playername” soulbound 1 “Playername”. I’m not sure what I’m doing wrong but if I could get some help that would be fantastic

**Comment by jacky8399** [comment]
Fixed in [v1.13.2](https://github.com/jacky8399/PortableBeacons/releases/tag/v1.13.2). Thanks for the report!
